project:
  type: website
  output-dir: docs

website:
  title: "Data Science Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css



